# Poetry

[[poetry]]
name = "Back to Research"
weight = 1
url = "/"

[[poetry]]
name = "Book"
weight = 2
url = "#book"

[[poetry]]
name = "About"
weight = 3
url = "#about"

# [[poetry]]
# name = "Tour"
# weight = 3
# url = "#tour"

[[poetry]]
name = "Videos"
weight = 5
url = "#watch"

[[poetry]]
name = "Contact"
weight = 6
url = "#contact"

# Research

[[research]]
name = "Bio"
weight = 10
url = "/#bio"

[[research]]
name = "Publications"
weight = 20
url = "/#publications"

[[research]]
name = "Projects"
weight = 30
url = "/#projects"

[[research]]
name = "Blog"
weight = 40
url = "/#blog"

[[research]]
name = "Experience"
weight = 50
url = "/experience"

[[research]]
name = "Poetry"
weight = 60
url = "/poetry"





