# Poetry

[[poetry]]
name = "Book"
weight = 1
url = "#book"

[[poetry]]
name = "About"
weight = 2
url = "#about"

# [[poetry]]
# name = "Tour"
# weight = 3
# url = "#tour"

# [[poetry]]
# name = "Watch"
# weight = 4
# url = "#watch"

[[poetry]]
name = "Contact"
weight = 5
url = "#contact"

# Research

[[research]]
name = "Bio"
weight = 10
url = "/research/#bio"

[[research]]
name = "Blog"
weight = 20
url = "/research/#blog"

[[research]]
name = "Experience"
weight = 30
url = "/research/experience"

[[research]]
name = "Projects"
weight = 40
url = "/research/#projects"

[[research]]
name = "Publications"
weight = 50
url = "/research/#publications"


