HUGO_VERSION = "0.125.4"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo && npx pagefind --source 'public'"

[context.split1.environment]
HUGO_VERSION = "0.125.4"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL && npx pagefind --source 'public'"

[context.deploy-preview.environment]
HUGO_VERSION = "0.125.4"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL && npx pagefind --source 'public'"

[context.branch-deploy.environment]
HUGO_VERSION = "0.125.4"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"