# Meta Data for SEO

## Homepage
title = "Kalvik Jakkala"
titleSeparator = "|"
description = "Kalvik Jakkala's personal website"
baseURL = "https://itskalvik.com/"

## Open Graph
images = ["images/og-image.jpg"]
ogLocale = "en_US"
domainTLD = "itskalvik.com"
titleHome = "Kalvik Jakkala"

## Twitter Cards
twitterSite = "@itskalvik"
twitterCreator = "@itskalvik"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Kalvik Jakkala"
schemaAuthor = "Kalvik Jakkala"
schemaAuthorTwitter = "https://twitter.com/itskalvik"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/itskalvik"
schemaAuthorGitHub = "https://github.com/itskalvik"
schemaLocale = "en-US"
schemaLogo = "images/og-image.jpg"
schemaLogoWidth = 1280
schemaLogoHeight = 640
schemaImage = "images/og-image.jpg"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/itskalvik"
schemaLinkedIn = "https://www.linkedin.com/in/itskalvik"
schemaGitHub = "https://github.com/itskalvik"
schemaSection = "blog"

# Images
favicon = "images/favicon.png"
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Google Tag Manager
googleTagManagerId = ""

[math]
enable = true

[header]
show_theme_chooser = true
show_search = true

[appearance]
mode = "system"